services:
  mongodb:
    image: mongo:7
    container_name: tech-challenge-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: techchallenge
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tech-challenge-network

  backend-api:
    build:
      context: ./submodules/backend
      dockerfile: ./Dockerfile
    container_name: tech-challenge-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:password@mongodb:27017/techchallenge?authSource=admin
      - PORT=5000
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    networks:
      - tech-challenge-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5001
    container_name: tech-challenge-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend-api
    networks:
      - tech-challenge-network

volumes:
  mongo_data:

networks:
  tech-challenge-network:
    driver: bridge
